name: nats
version: '2.1.9'
summary: A simple, secure and high performance open source messaging system
description: |
  NATS.io is a simple, secure and high performance open source messaging system for cloud
  native applications, IoT messaging, and microservices architectures.
confinement: strict
grade: stable

plugs:
  nats-config:
    interface: content
    content: nats-cfg
    target: $SNAP/external

apps:
  server:
    daemon: simple
    command: bin/start-nats.sh
    plugs: [network-bind]

  getconfig:
    command: bin/getconfig

parts:
  getconfig:
    plugin: dump
    source: getconfig

  nats:
    plugin: go
    go-importpath: github.com/nats-io/nats-server/v2
    source: https://github.com/nats-io/nats-server
    source-tag: v2.1.9
    source-type: git
    build-snaps:
    # Upstream still builds their releases with 1.14
    - go/1.14/stable
    override-build: |
      unset GOPATH
      export GO111MODULE=on
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/bin
      go build -mod vendor -o nats-server
      cp nats-server "$SNAPCRAFT_PART_INSTALL"/bin
    stage:
    - bin/nats-server

  scripts:
    plugin: dump
    source: scripts
    organize:
      start-nats.sh: bin/start-nats.sh
      functions.sh: bin/functions.sh
    stage:
    - bin/start-nats.sh
    - bin/functions.sh
